name: Fetch News

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: main

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: automation-scripts/News
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"
          
      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: yarn start

      - name: Move news.json
        run: git mv news.json ../../ui/public/news.json
        
      - name: Commit and push if changed
        run: |-
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add news.json
          git commit -m "Update news.json" || true
          git push
        working-directory: ui/public
