name: Fetch News

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: automation-scripts/News
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"
          
      - name: List directory contents
        run: ls -R     
        
      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
