name: Fetch News

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: main

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: automation-scripts/News
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"

      - name: List directory contents
        run: ls -R

      - name: PWD
        run: pwd

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Print current directory
        run: pwd

      - name: Run
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: yarn start

#       - name: Move data.json
#         run: git mv automation-scripts/News/data.json ../../ui/public/data.json

      - name: change directory
        run: |-
          cd ../..
          ls
        
      - name: Commit and push if changed
        run: |-
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data.json
          git commit -m "Update data.json" || true
          git push
